// Agent Reach v2.0 — Channel Definitions & Constants

import type { ChannelDef } from './types';

export const CHANNELS: ChannelDef[] = [
  {
    id: 'web',
    name: 'Web (Jina Reader)',
    nameZh: '网页',
    tier: 0,
    icon: 'Globe',
    color: 'emerald',
    description: 'Read any web page via Jina Reader API',
    descriptionZh: '通过 Jina Reader 读取任意网页',
    needsAuth: false,
    authType: 'none',
    backends: ['jina-reader'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    nameZh: 'YouTube',
    tier: 0,
    icon: 'Youtube',
    color: 'red',
    description: 'Video transcripts and metadata',
    descriptionZh: '视频字幕和元数据',
    needsAuth: false,
    authType: 'none',
    backends: ['yt-dlp'],
  },
  {
    id: 'rss',
    name: 'RSS Feeds',
    nameZh: 'RSS 订阅',
    tier: 0,
    icon: 'Rss',
    color: 'orange',
    description: 'Subscribe to RSS feeds',
    descriptionZh: '订阅 RSS 源',
    needsAuth: false,
    authType: 'none',
    backends: ['rss-parser'],
  },
  {
    id: 'v2ex',
    name: 'V2EX',
    nameZh: 'V2EX',
    tier: 0,
    icon: 'MessageSquare',
    color: 'slate',
    description: 'V2EX forum posts',
    descriptionZh: 'V2EX 论坛帖子',
    needsAuth: false,
    authType: 'none',
    backends: ['v2ex-api'],
  },
  {
    id: 'exa-search',
    name: 'Exa Search',
    nameZh: 'Exa 搜索',
    tier: 0,
    icon: 'Search',
    color: 'violet',
    description: 'AI-powered web search via Exa',
    descriptionZh: '通过 Exa 进行 AI 搜索',
    needsAuth: false,
    authType: 'none',
    backends: ['exa-api'],
  },
  {
    id: 'github',
    name: 'GitHub',
    nameZh: 'GitHub',
    tier: 0,
    icon: 'Github',
    color: 'zinc',
    description: 'GitHub repos, issues, code search',
    descriptionZh: 'GitHub 仓库、Issue、代码搜索',
    needsAuth: false,
    authType: 'none',
    backends: ['github-api'],
  },
  {
    id: 'wechat',
    name: 'WeChat Articles',
    nameZh: '微信公众号',
    tier: 0,
    icon: 'MessageCircle',
    color: 'green',
    description: 'WeChat public account articles',
    descriptionZh: '微信公众号文章',
    needsAuth: false,
    authType: 'none',
    backends: ['wechat-api'],
  },
  {
    id: 'twitter',
    name: 'Twitter / X',
    nameZh: 'Twitter / X',
    tier: 1,
    icon: 'Twitter',
    color: 'sky',
    description: 'Tweets, profiles, and trends',
    descriptionZh: '推文、用户资料和趋势',
    needsAuth: true,
    authType: 'cookie',
    backends: ['twitter-api'],
  },
  {
    id: 'bilibili',
    name: 'Bilibili',
    nameZh: '哔哩哔哩',
    tier: 1,
    icon: 'Tv',
    color: 'pink',
    description: 'Bilibili videos and comments',
    descriptionZh: 'B站视频和评论',
    needsAuth: true,
    authType: 'cookie',
    backends: ['bili-api'],
  },
  {
    id: 'weibo',
    name: 'Weibo',
    nameZh: '新浪微博',
    tier: 1,
    icon: 'AtSign',
    color: 'rose',
    description: 'Weibo posts and hot topics',
    descriptionZh: '微博帖子和热搜',
    needsAuth: false,
    authType: 'none',
    backends: ['weibo-api'],
  },
  {
    id: 'reddit',
    name: 'Reddit',
    nameZh: 'Reddit',
    tier: 1,
    icon: 'MessageCircle',
    color: 'orange',
    description: 'Reddit posts, comments, subreddits',
    descriptionZh: 'Reddit 帖子和评论',
    needsAuth: true,
    authType: 'cookie',
    backends: ['reddit-api'],
  },
  {
    id: 'xiaohongshu',
    name: 'XiaoHongShu',
    nameZh: '小红书',
    tier: 1,
    icon: 'BookOpen',
    color: 'red',
    description: 'XiaoHongShu posts and notes',
    descriptionZh: '小红书笔记',
    needsAuth: true,
    authType: 'cookie',
    backends: ['xhs-api'],
  },
  {
    id: 'xueqiu',
    name: 'Xueqiu',
    nameZh: '雪球',
    tier: 1,
    icon: 'TrendingUp',
    color: 'blue',
    description: 'Stock market data and discussions',
    descriptionZh: '股票数据和讨论',
    needsAuth: true,
    authType: 'cookie',
    backends: ['xueqiu-api'],
  },
  {
    id: 'xiaoyuzhou',
    name: 'XiaoYuZhou',
    nameZh: '小宇宙',
    tier: 1,
    icon: 'Headphones',
    color: 'purple',
    description: 'Podcast transcription via Whisper',
    descriptionZh: '播客转录',
    needsAuth: true,
    authType: 'apikey',
    backends: ['groq-whisper'],
  },
  {
    id: 'douyin',
    name: 'Douyin',
    nameZh: '抖音',
    tier: 2,
    icon: 'Music',
    color: 'fuchsia',
    description: 'Douyin video content',
    descriptionZh: '抖音视频内容',
    needsAuth: false,
    authType: 'none',
    backends: ['douyin-api'],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    nameZh: 'LinkedIn',
    tier: 2,
    icon: 'Linkedin',
    color: 'blue',
    description: 'LinkedIn profiles and jobs',
    descriptionZh: 'LinkedIn 资料和职位',
    needsAuth: true,
    authType: 'browser',
    backends: ['linkedin-api'],
  },
];

export const TIER_LABELS: Record<number, { label: string; labelZh: string; color: string }> = {
  0: { label: 'Zero-Config', labelZh: '零配置', color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30' },
  1: { label: 'Free Key', labelZh: '免费密钥', color: 'bg-amber-500/20 text-amber-400 border-amber-500/30' },
  2: { label: 'Complex', labelZh: '复杂配置', color: 'bg-red-500/20 text-red-400 border-red-500/30' },
};

export const HEALTH_COLORS: Record<string, string> = {
  ok: 'bg-emerald-500',
  warn: 'bg-amber-500',
  off: 'bg-zinc-500',
  error: 'bg-red-500',
  unknown: 'bg-zinc-600',
};

export const HEALTH_LABELS: Record<string, string> = {
  ok: 'Online',
  warn: 'Warning',
  off: 'Offline',
  error: 'Error',
  unknown: 'Unknown',
};

export const JINA_READER_URL = 'https://r.jina.ai/';

export const MEMORY_LEVELS = [
  { level: 0, name: 'Meta', nameZh: '元认知', description: 'Core identity, goals, and operational boundaries', descriptionZh: '核心身份、目标和运营边界' },
  { level: 1, name: 'Insight', nameZh: '洞察', description: 'Cross-domain insights and patterns', descriptionZh: '跨领域洞察和模式' },
  { level: 2, name: 'Fact', nameZh: '事实', description: 'Verifiable facts and knowledge', descriptionZh: '可验证的事实和知识' },
  { level: 3, name: 'SOP', nameZh: '流程', description: 'Standard operating procedures', descriptionZh: '标准操作流程' },
  { level: 4, name: 'History', nameZh: '历史', description: 'Task execution history', descriptionZh: '任务执行历史' },
];
